version: '3.8'


services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 3399:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: always

  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    restart: always

  serv:
    build: ./nginx
    ports:
      - 3001:80
    depends_on:
      - app
    restart: always

  logs:
    build: ./logs
    restart: always


volumes:
  postgres_data:
