version: '3.8'


services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 3399:8000
    env_file:
      - ./.env.dev
    networks:
      - transcend
    depends_on:
      - db
    restart: always

  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - transcend
    restart: always

  serv:
    build: ./nginx
    ports:
      - 3001:80
    networks:
      - transcend
    depends_on:
      - app
    restart: always

networks:
  transcend:
    driver: bridge

volumes:
  postgres_data:
  elsearch:

#https://github.com/deviantony/docker-elk
