# Generated by Django 4.2.3 on 2024-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
                ('playerA', models.CharField(default='', max_length=40)),
                ('pointsA', models.IntegerField(default=0)),
                ('playerB', models.CharField(default='', max_length=40)),
                ('pointsB', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='playerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('gamesWon', models.IntegerField(default=0)),
                ('gamesLost', models.IntegerField(default=0)),
                ('numTournament', models.IntegerField(default=0)),
                ('numTourneyWins', models.IntegerField(default=0)),
                ('isRegistered', models.BooleanField(default=False)),
                ('isLogged', models.BooleanField(default=False)),
            ],
        ),
    ]
