# Generated by Django 4.2.3 on 2024-11-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='gameID',
        ),
    ]
