# Generated by Django 5.1.4 on 2024-12-04 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_history_gamedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='gameDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 15, 33, 9, 543950, tzinfo=datetime.timezone.utc)),
        ),
    ]
