# Generated by Django 5.1.4 on 2024-12-05 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_history_gamedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='gameDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 20, 58, 45, 292596, tzinfo=datetime.timezone.utc)),
        ),
    ]
